PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE test (name TEXT, timestamp TEXT);
INSERT INTO "test" VALUES('TOM',NULL);
INSERT INTO "test" VALUES('GEORGE',NULL);
INSERT INTO "test" VALUES('JACK',NULL);
INSERT INTO "test" VALUES('JOHN',NULL);
COMMIT;